### ISSUE TITLE
how to shorten the project file path

### ISSUE THREAD

**Issue by gdanov** [joaotavora/breadcrumb#11] opened 2023-06-19 08:48 UTC
I have typescript + eglot project. Breadcrumb works great, but I can't customize the file path portion. My file path looks like this
```
<project name>/native/src/components/common.tsx : <the in-file position>
```

I tried limiting the `breadcrumb-project-max-length` but nothing changes. Probably I have the wrong idea what this variable does.

anyhow, I'd like to have flexibility to how the file path is displayed. Ideally I'd like to be able to provide formatter function, ideally local to the project or the folder? This is monorepo and in each (sub) project I'd shorten different part to help me orient myself better.

**Comment by joaotavora** [comment] 2023-09-04 16:08
Hi, I was just working on this.  You are probably using the variable correctly but have to clear a cache called `breadcrumb--cached-project-crumbs`.  let me know it it works.  I might need a better cache invalidation mechanism, or just get rid of the cache.  Patches welcome.

**Comment by gdanov** [comment] 2023-09-06 13:33
this var has weird value (based on my uninformed assumption):
```
#("xxxx-edu/n/s/c/ledger/goals.tsx" 0 11
	(breadcrumb-dont-shorten t))
```

how should I reset it?

the breadcrumb right now looks like this:

```
<project name>/a/b/c/d/folder/file.tsx
```

**Comment by joaotavora** [comment] 2023-09-06 13:39
I've removed that variable in the latest version, so you shouldn't have any more problems

**Comment by joaotavora** [comment] 2023-09-07 14:53
Closing, as I'm 99% the problem is solved.  Let me know if it isn't and I will reopen.

**Closed as completed by joaotavora** 2023-09-07 14:53 UTC
